Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "spec/spec_helper.rb"
